comments should not change parser state
cucumber/gherkin pull request #334
Opened 2024-12-09 10:00 UTC by jacob-wieland-gematik

### 🤔 What's changed?

### ⚡️ What's your motivation? 

### 🏷️ What kind of change is this?

- :book: Documentation (improvements without changing code)
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
- :bug: Bug fix (non-breaking change which fixes a defect)
- :zap: New feature (non-breaking change which adds new behaviour)
- :boom: Breaking change (incompatible changes to the API)

### ♻️ Anything particular you want feedback on?

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://github.com/cucumber/.github/tree/main?tab=coc-ov-file)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

2024-12-09 13:30 UTC, mpkorstanje commented
The parser is generated. To change the parser you'll have to change the grammar.

https://github.com/cucumber/gherkin/blob/00fcc43f56ca69c6dbd68e85a41129a0f3b6b915/gherkin.berp#L35-L38

2024-12-10 14:18 UTC, jacob-wieland-gematik commented
I have changed the grammar to allow any mixture of empty lines, comments and other-lines as the description. 

Extracting only the other-lines from the Description-AST-Node (as before) should yield the description-text without the comments and empty lines. 

Only difference is now that a collection of ony empty-lines and comments would yield an empty description text instead of a non-existing Description node.

2024-12-11 11:16 UTC, jacob-wieland-gematik commented
Changed the grammar in a way that is more consistent with the former test cases (treating empty lines inside description blocks as '#Other' lines).

2025-01-05 13:38 UTC, kieran-ryan commented
@jacob-wieland-gematik, installing `berp` on the [`test-codegen` workflow](https://github.com/cucumber/gherkin/blob/16efcc9a4bc0208ec4049be33c3f10d2e318298f/.github/workflows/test-codegen.yml) and running the tests on the [`test-dotnet`](https://github.com/cucumber/gherkin/blob/16efcc9a4bc0208ec4049be33c3f10d2e318298f/.github/workflows/test-dotnet.yml) workflow are failing owing to incompatibilities with `ubuntu-24.04` which has now been promoted as the `ubuntu-latest` GitHub runner and is being picked up in the pipeline. I have pinned those workflows to `ubuntu-22.04` for now (#348); and you may want to pull in those changes to allow those workflow steps to proceed.

2025-01-06 12:55 UTC, jacob-wieland-gematik commented
@kieran-ryan I have rebased on latest main and updated a tokens file. Can you approve the checks again?

2025-01-07 10:21 UTC, jacob-wieland-gematik commented
Added dialect.c which was missing for some reason. Please approve checks @kieran-ryan

2025-01-08 17:56 UTC, jacob-wieland-gematik commented
I am not able to generate Parser.php locally, so not sure what to do here @kieran-ryan

2025-01-09 09:30 UTC, mpkorstanje commented
@jacob-wieland-gematik are you able to generate the php parser using the docker container?

https://github.com/cucumber/gherkin/blob/main/CONTRIBUTING.md#generating-parsers

2025-01-09 12:31 UTC, jacob-wieland-gematik commented
> @jacob-wieland-gematik are you able to generate the php parser using the docker container?
> 
> https://github.com/cucumber/gherkin/blob/main/CONTRIBUTING.md#generating-parsers

No, there seems to be a problem doing that under windows (probably CRLF vs LF related) that hinders this generation.

When change the CRLF of the generated classes.php to LF and then do the generation steps manually, I was able to generate Parser.php

@mpkorstanje

2025-01-10 20:35 UTC, jacob-wieland-gematik commented
When will this be merged? @mpkorstanje @kieran-ryan

2025-01-12 16:39 UTC, mpkorstanje commented
Always a bit hard to say. :smile: 

But hopefully .

2025-01-12 16:45 UTC, mpkorstanje requested changes
Looks good overall. I am missing a test with a comment in the middle of a description.

Do you have time to add a scenario to `descirptions.feature`?

2025-01-13 10:47 UTC, jacob-wieland-gematik commented
> Looks good overall. I am missing a test with a comment in the middle of a description.
> 
> Do you have time to add a scenario to `descirptions.feature`?

I can try.

2025-01-13 12:58 UTC, jacob-wieland-gematik commented
Added tests @mpkorstanje

2025-01-14 11:00 UTC, jacob-wieland-gematik commented
Added missing compare files. @mpkorstanje

2025-01-16 11:02 UTC, jacob-wieland-gematik commented
Seems all is well now. Any chance we can merge this? @mpkorstanje @kieran-ryan

2025-01-23 13:41 UTC, mpkorstanje approved these changes
Cheers! Looks good now. Much appreciated.

2025-01-23 13:42 UTC, merged